require 'csv'

namespace :import do
  desc "Import users from CSV file"
  task users: :environment do
    csv_file = ENV['CSV_FILE'] || 'user_contribution.csv'

    unless File.exist?(csv_file)
      puts "Error: File #{csv_file} not found"
      puts "Usage: rails import:users CSV_FILE=path/to/file.csv"
      exit 1
    end

    success_count = 0
    error_count = 0
    skip_count = 0
    errors = []

    puts "Starting import from #{csv_file}..."
    puts "=" * 80

    CSV.foreach(csv_file, headers: true, encoding: 'UTF-8') do |row|
      name = row['Name']&.strip
      block_address = row['Address']&.strip&.upcase
      phone = row['Phone']&.strip

      # Skip if no address
      if block_address.blank?
        skip_count += 1
        next
      end

      # Find or create address
      address = Address.find_or_create_by(block_address: block_address) do |addr|
        addr.free = false
      end

      # Skip if no name and no phone (empty row)
      if name.blank? && phone.blank?
        puts "⊘ Skipped #{block_address}: No name and no phone"
        skip_count += 1
        next
      end

      # Set default name if blank
      if name.blank?
        name = "Warga #{block_address}"
      end

      # Skip if no phone (required for user)
      if phone.blank?
        puts "⊘ Skipped #{block_address} (#{name}): No phone number"
        skip_count += 1
        next
      end

      begin
        # Check if user already exists with this phone
        # The normalize_phone_number will handle format conversion
        existing_user = User.find_by_phone(phone)

        if existing_user
          # User exists, just add address if not already connected
          unless existing_user.addresses.include?(address)
            existing_user.add_address!(address, primary: false, kk: true)
            puts "✓ Updated #{block_address}: Added address to existing user #{existing_user.name} (#{existing_user.phone_number})"
            success_count += 1
          else
            puts "⊘ Skipped #{block_address}: User #{existing_user.name} already connected"
            skip_count += 1
          end
        else
          # Create new user
          user = User.new(
            name: name,
            phone_number: phone,
            role: 1 # Warga
          )

          # Password and email will be auto-generated by callbacks

          if user.save
            # Add address as head of family
            user.add_address!(address, primary: true, kk: true)
            puts "✓ Created #{block_address}: #{name} (#{user.phone_number})"
            success_count += 1
          else
            error_msg = "#{block_address}: #{name} - #{user.errors.full_messages.join(', ')}"
            errors << error_msg
            puts "✗ Failed #{error_msg}"
            error_count += 1
          end
        end

      rescue StandardError => e
        error_msg = "#{block_address}: #{name} - #{e.message}"
        errors << error_msg
        puts "✗ Error #{error_msg}"
        error_count += 1
      end
    end

    puts "=" * 80
    puts "Import completed!"
    puts "✓ Success: #{success_count}"
    puts "⊘ Skipped: #{skip_count}"
    puts "✗ Errors: #{error_count}"

    if errors.any?
      puts "\nErrors:"
      errors.each { |error| puts "  - #{error}" }
    end
  end

  desc "Import users from CSV with dry run (preview only)"
  task users_preview: :environment do
    csv_file = ENV['CSV_FILE'] || 'user_contribution.csv'

    unless File.exist?(csv_file)
      puts "Error: File #{csv_file} not found"
      exit 1
    end

    puts "Preview mode - no data will be saved"
    puts "=" * 80

    valid_count = 0
    skip_count = 0

    CSV.foreach(csv_file, headers: true, encoding: 'UTF-8') do |row|
      name = row['Name']&.strip
      block_address = row['Address']&.strip&.upcase
      phone = row['Phone']&.strip

      if block_address.blank?
        skip_count += 1
        next
      end

      if name.blank? && phone.blank?
        puts "⊘ Would skip #{block_address}: Empty row"
        skip_count += 1
        next
      end

      if phone.blank?
        puts "⊘ Would skip #{block_address} (#{name || 'No name'}): No phone"
        skip_count += 1
        next
      end

      name = "Warga #{block_address}" if name.blank?

      # Check if user exists
      existing_user = User.find_by_phone(phone)

      if existing_user
        puts "ℹ Would update: #{block_address} → existing user #{existing_user.name} (#{existing_user.phone_number})"
      else
        puts "✓ Would create: #{block_address} → #{name} (phone: #{phone})"
      end

      valid_count += 1
    end

    puts "=" * 80
    puts "Preview completed!"
    puts "✓ Would process: #{valid_count}"
    puts "⊘ Would skip: #{skip_count}"
    puts "\nTo actually import, run: rails import:users CSV_FILE=#{csv_file}"
  end
end
