development:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL") { "postgresql://localhost/puriayana_development" } %>

test:
  adapter: test

production:
  adapter: postgresql
  url: <%= ENV.fetch("DATABASE_URL", "postgresql://localhost/puriayana_production") %>
  channel_prefix: puriayana_production
